# Generated by Django 4.2.5 on 2023-09-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('tmdb_id', models.IntegerField(null=True, unique=True)),
                ('imdb_id', models.CharField(blank=True, max_length=20, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('poster_path', models.CharField(blank=True, max_length=255, null=True)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('trailer_key', models.CharField(blank=True, max_length=255, null=True)),
                ('imdb_rating', models.CharField(blank=True, max_length=10, null=True)),
                ('tmdb_popularity', models.CharField(blank=True, max_length=10, null=True)),
                ('rotten_tomatoes_rating', models.CharField(blank=True, max_length=10, null=True)),
                ('metacritic_rating', models.CharField(blank=True, max_length=10, null=True)),
                ('director', models.CharField(blank=True, max_length=255, null=True)),
                ('domestic_box_office', models.CharField(blank=True, max_length=100, null=True)),
                ('now_playing', models.BooleanField(default=False)),
                ('mpa_rating', models.CharField(blank=True, max_length=20, null=True)),
                ('genres', models.ManyToManyField(blank=True, to='webapp.genre')),
            ],
        ),
    ]
