# Generated by Django 4.2.5 on 2023-09-17 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_delete_users_movies_imdbrating_movies_runtime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='synopsis',
            new_name='description',
        ),
    ]
