# Generated by Django 4.2.5 on 2023-09-17 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_rename_synopsis_movies_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('runtime', models.IntegerField()),
                ('imdbRating', models.IntegerField()),
                ('mpaRating', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('tagline', models.TextField()),
                ('whereToWatch', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Movies',
        ),
    ]
