# Generated by Django 4.2.5 on 2023-11-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_userprofile_biography'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_pic',
            field=models.CharField(choices=[('default.jpg', 'Default')], default='default.jpg', max_length=100),
        ),
    ]
