# Generated by Django 4.2.5 on 2023-09-17 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_movie_delete_movies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='description',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='imdbRating',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='mpaRating',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='runtime',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='tagline',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='whereToWatch',
        ),
    ]
