# Generated by Django 4.2.5 on 2023-09-27 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_movie_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamingProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo_path', models.CharField(blank=True, max_length=255, null=True)),
                ('provider_id', models.IntegerField(unique=True)),
            ],
        ),
    ]
