# Generated by Django 4.2.5 on 2023-09-19 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_genre_remove_movie_releaseyear_movie_overview_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='tmdb_id',
        ),
    ]
