# Generated by Django 4.2.5 on 2023-12-02 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_movie_top_streaming_providers'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamingprovider',
            name='ranking',
            field=models.IntegerField(default=0),
        ),
    ]
