# Generated by Django 4.2.5 on 2023-09-29 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_movie_streaming_providers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='tmdb_id',
            field=models.IntegerField(db_index=True, null=True, unique=True),
        ),
    ]
