# Generated by Django 4.2.5 on 2023-09-19 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_movie_release_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
