# Generated by Django 4.2.5 on 2023-09-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_alter_movie_tmdb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='recommended_movies',
            field=models.ManyToManyField(blank=True, related_name='recommended_by', to='webapp.movie'),
        ),
    ]
