# Generated by Django 4.2.5 on 2023-09-19 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_movie_trailer_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='box_office',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='imdb_rating',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='metacritic_rating',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='rotten_tomatoes_rating',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
