# Generated by Django 4.2.5 on 2023-12-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_alter_streamingprovider_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdb_rating_num',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
