# Generated by Django 4.2.5 on 2023-09-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_movie_created_at_alter_movie_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='recommended_movies',
        ),
        migrations.AddField(
            model_name='movie',
            name='recommended_movie_data',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
