# Generated by Django 4.2.5 on 2023-09-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_movie_box_office_movie_director_movie_imdb_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='now_playing',
            field=models.BooleanField(default=False),
        ),
    ]
