# Generated by Django 4.2.5 on 2023-09-20 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_movie_now_playing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='box_office',
            new_name='domestic_box_office',
        ),
    ]
