# Generated by Django 4.2.5 on 2023-10-04 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_remove_movie_recommended_movies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='letterboxd_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
