# Generated by Django 4.2.5 on 2023-09-20 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_rename_box_office_movie_domestic_box_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
