# Generated by Django 4.2.5 on 2023-10-08 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_movie_letterboxd_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='watchlist_name',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
