# Generated by Django 4.2.5 on 2024-03-01 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_movierating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.CharField(choices=[('default.png', 'Default'), ('man_suit.png', 'Man in Suit'), ('man_hoodie.png', 'Man in Hoodie'), ('woman_glasses.png', 'Woman with Glasses'), ('woman_suit.png', 'Woman in Suit'), ('girl_bow.png', 'Girl with Bow'), ('boy_smile.png', 'Boy with Smile'), ('man_beard.png', 'Man with Beard')], default='default.png', max_length=100),
        ),
    ]
