# Generated by Django 4.2.5 on 2024-03-03 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_movie_actors_alter_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='shortened_title',
            field=models.CharField(blank=True, max_length=49),
        ),
    ]
