# Generated by Django 4.2.5 on 2023-10-08 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_alter_watchlist_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='name',
            new_name='watchlist_name',
        ),
    ]
