# Generated by Django 4.2.5 on 2023-09-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_movie_mpa_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdb_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
