# Generated by Django 4.2.5 on 2024-03-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_movie_shortened_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='justwatch_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
