# Generated by Django 4.2.5 on 2023-09-22 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_movie_backdrop_path_movie_tmdb_popularity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='backdrop_path',
        ),
    ]
