# Generated by Django 4.2.5 on 2024-03-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_movie_original_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='letterboxd_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
