# Generated by Django 4.2.5 on 2023-09-22 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_remove_movie_backdrop_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='is_popular',
        ),
    ]
